### ISSUE TITLE
No jar file?

### ISSUE THREAD

**Issue by karimo94** [apex-enterprise-patterns/fflib-apex-mocks#105]
I'm trying to leverage this so I can make my own mock tests but I cannot seem to find the jar file used in generating the interface and mock classes. Any ideas? Am I missing something here?

**Comment by ImJohnMDaniel** [comment]
@karimo94 -- The JAR file approach has not been needed for a couple of years now. The mocking framework now utilizes the stubbing API to manage the mocks (see the [fflib_ApexMocks class, "mock" method](https://github.com/apex-enterprise-patterns/fflib-apex-mocks/blob/master/sfdx-source/apex-mocks/main/classes/fflib_ApexMocks.cls#L65) for more details).  Also check out the fflib_ApexMocksTest test class for a working example.  Hope this helps.
