### ISSUE TITLE
Install help needed

### ISSUE THREAD

**Issue by aday12345** [apex-enterprise-patterns/fflib-apex-mocks#113]
Hi, I installed this about a month ago into a sandbox with no issues. And today I want to add this to our prod org but i keep getting an error when i try to install it:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command

Can anyone help i need to get FFlib mocks and common deployed into production

**Comment by ImJohnMDaniel** [comment]
@aday12345 -- FFLIB mocks and common deploy like any other Apex classes.  There is nothing special about the deployment.

You error message refers to the "Heroku CLI".  FFLib Apex classes most certainly have nothing to do with Heroku aspects.

Are you using some sort of service to deploy the code to production (i.e. Copado, Flosum, etc.)???

**Comment by aday12345** [comment]
no, i am using the 'Deploy to Salesforce' button found on the readme
https://github.com/apex-enterprise-patterns/fflib-apex-mocks/tree/master

**Comment by ImJohnMDaniel** [comment]
Ok. So this is an issue with the Heroku app that does the deployment and not an issue with this codebase.

You can post issues to @afawcett on that GitHub codebase here --> https://github.com/afawcett/githubsfdeploy/issues.  Bear in mind, that project does not offer guaranteed support nor any type of SLA.

Your best bet is to download the Apex Mocks and Apex Common repos and deploy them using the `sfdx force:source:deploy` command against your production org.

**Comment by aday12345** [comment]
ok, thanks
