### ISSUE TITLE
renderStoredEmailTemplate returns with an error System.EmailTemplateRenderException: INVALID_CROSS_REFERENCE_KEY: invalid cross reference id when passing Ids generated from fflib_IDGenerator

### ISSUE THREAD

**Issue by raffaelle09** [apex-enterprise-patterns/fflib-apex-mocks#127]
Is there anyway to render the email template body in the test class without committing the referenced records in the database?

just a quick sample:

    @isTest
    private static void renderEmailTemplate (){
        
        EmailTemplate temp = [SELECT Id from EmailTemplate LIMIT 1];
        Id accId = fflib_IDGenerator.generate(Account.SObjectType);
        Id conId = fflib_IDGenerator.generate(Contact.SObjectType);
        
        Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(temp.Id, conId, accId);
    }

**Comment by ImJohnMDaniel** [comment]
@raffaelle09, thanks for reaching out.  There is no feature in ApexMocks to achieve this.  You may have success by querying the EmailTemplate table and try your own merge to the template.
