### ISSUE TITLE
Deploy to salesforce is not working

### ISSUE THREAD

**Issue by jackTylerDurden** [apex-enterprise-patterns/fflib-apex-mocks#133]
Description -
I tried deploying this repo to my developer edition salesforce instance but I'm getting following whenever I login to salesforce - 

Unhandled Exception : java.lang.RuntimeException: /app/.local/share/sfdx/client/7.175.0-a62760c/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /app/.local/share/sfdx/client/7.175.0-a62760c/bin/node)

**To Reproduce**

1. Created a developer edition (free) salesforce instance.
2. Clicked on the deploy to Salesforce button of this repo.
3. Selected type of instance as Production/Developer
4. Clicked on Login to Salesforce button

**Expected behavior**
Classes and Labels should have been deployed.

**Screenshots and text of error observed**
If applicable, add screenshots to help explain your problem. Also, paste the text of the raw error into the issue as well so that it can be found by others via search.

**Version**
Did you try to reproduce the problem against the latest fflib-apex-mocks code?
Yes.

**Comment by ImJohnMDaniel** [comment]
@jackTylerDurden 
- are you having issues deploying this to scratch org?
- Have you had any issues deploying anything else to that developer edition org?

**Comment by jackTylerDurden** [comment]
1. are you having issues deploying this to a scratch org? - No. I signed up and created a developer edition org.
2. Have you had any issues deploying anything else to that developer edition org? - This is the first time I'm deploying something to salesforce using this tool.

**Comment by ImJohnMDaniel** [comment]
Understood.

Considering this code repo is deployed successfully to hundreds of orgs every day, I'm inclined to think that the issues you are seeing are somehow related to your specific setup of the CLI.  I would recommend opening up an issue with the Salesforce CLI project directly - https://github.com/forcrdotcom/cli/issues

**Comment by ImJohnMDaniel** [comment]
OOOHHHH.  You used the Heroku deployment button on the project and were not using the Salesforce CLI locally to deploy the codebase.  Ok, I understand now.

And apologies, I mis-typed the link above.  It should have been https://github.com/forcedotcom/cli/issues 

Ok, the Heroku deployment tool is not controlled by AEP.  We just use it.  I will reach out to the folks that maintain it and ask them to look into this.  In the meantime, I would recommend using the Salesforce CLI to deploy the ApexMocks framework to your Developer Edition.

**Comment by ImJohnMDaniel** [comment]
@jackTylerDurden -- Can you give it another try please?  I just used the tool to deploy this codebase and it succeeded.

**Comment by cjab-creator** [comment]
Hello! Today I'm facing the same problem that @jackTylerDurden described

Unhandled Exception : java.lang.RuntimeException: /app/.local/share/sfdx/client/7.176.1-458b658/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /app/.local/share/sfdx/client/7.176.1-458b658/bin/node) 

@ImJohnMDaniel is there a tutorial to deploy ApexMocks using Salesforce CLI?

**Comment by ImJohnMDaniel** [comment]
@cjab-creator -- Just to be clear.  Are you also trying to deploy the code base using the "Deploy to Salesforce" button?

>@ImJohnMDaniel is there a tutorial to deploy ApexMocks using Salesforce CLI?
- Not really.  ApexMocks deploys like any other project would via the Salesforce CLI.  It is just simply GIT Cloning the ApexMocks repo locally and then [executing the `force:source:deploy` command](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_deploy)

**Comment by anishgarg18** [comment]
@ImJohnMDaniel 
Hello John.
i am also facing the same error - Unhandled Exception : java.lang.RuntimeException: /app/.local/share/sfdx/client/7.176.1-458b658/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /app/.local/share/sfdx/client/7.176.1-458b658/bin/node).
And i am trying to deploy the code base using the "Deploy to Salesforce" button only.

**Comment by ImJohnMDaniel** [comment]
G'day folks.  It's confirmed that this is an issue with the GitHubSFDeploy tool and not the ApexMocks project.

The open issue to follow is afawcett/githubsfdeploy#53

I hope this helps.

Cheers!

**Comment by afawcett** [comment]
Just worked for me... hmmm... 
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/1167760/204435227-c521d0d3-040b-42eb-8be8-9974367f6bb3.png">

**Comment by afawcett** [comment]
Posted a further update here https://github.com/afawcett/githubsfdeploy/issues/53
