### ISSUE TITLE
IDGenerator : Generating Salesforce Object ID under the new structure

### ISSUE THREAD

**Issue by n4n3** [apex-enterprise-patterns/fflib-apex-mocks#143]
As per the latest Salesforce Release notes, Salesforce Object ID is now refined to use three characters for Server IDs (https://help.salesforce.com/s/articleView?id=release-notes.rn_hyperforce_object_id.htm&release=246&type=5).

Previously, a valid Salesforce Object ID had a two-character Server ID or Instance ID as the 4th and 5th characters in the overall 15-18 characters. With this change, Salesforce now generates three-character Server IDs, which are the 4th, 5th, and 6th characters in the Object ID. This update can cause test cases to fail if manually generating salesforce Ids using custom code in a manner that does not account for this new structure.

The class "fflib_IDGenerator.cls" describes sObject ID structure to be used in mock. Salesforce was not able to confirm if the current class would require an update due to this release.

Do you happen to know if a change will be required in this class to adjust?

If so, do you plan to release an update for the class?

**Comment by stohn777** [comment]
Hello.

@n4n3, thanks for bringing this matter up for discussion.

Currently this ID-generator class only addresses the SObject ID with the remainder of the characters being zeros except for the sequence numbers being converted to characters.  ID mocking is intended for in-memory only SObject mocking and not intended to be used in conjunction with the SObject's actual data store.  To date, we've not had reports of the two-character, server ID being an issue, while not be implemented.

I'd would NOT expect this change to affect the intended usage of the framework's ID generator after the ID refinement.

@fishofprey, can you confirm whether the Apex implementation of the ID class will be changing with API Version 59 to require a valid three-character, server ID?

Regards.

**Comment by FishOfPrey** [comment]
Looking at [fflib_IDGenerator.cls](https://github.com/apex-enterprise-patterns/fflib-apex-mocks/blob/b030fca1a2e15f94dfec93f5a0610909ecdf5bb2/sfdx-source/apex-mocks/main/classes/fflib_IDGenerator.cls#L39) shows it increments the fake IDs starting from 1.

Based on the pattern, the server ID portion of the ID will remain zeros until they hit 1,000,000,000 generated fake IDs.

So as long as you aren't generating billions of fake IDs in a test run it won't overflow into the server ID reserved characters. If you are hitting billions of IDs in a test context you likely have other issues to address 😀

**Comment by n4n3** [comment]
Thanks a ton for the response, you rock <3
