### ISSUE TITLE
Code Coverage Issue with fflib_InvocationOnMock Class

### ISSUE THREAD

**Issue by lb14447** [apex-enterprise-patterns/fflib-apex-mocks#147]
**Describe the bug**
I am encountering a code coverage issue with the fflib_InvocationOnMock class from the fflib-apex-mocks library. The current test coverage for this class is only 55.556%, which is below the required 75% threshold for deployment in Salesforce.

**To Reproduce**

Unfortunately, I cannot provide a public GitHub repo with a full SFDX project at this time. However, the issue is reproducible in a scratch org with just the fflib-apex-mocks project deployed.

    Deploy the fflib-apex-mocks project into a new Salesforce scratch org.
    Run the test classes associated with the fflib-apex-mocks library.
    Observe the code coverage report.

**Expected behavior**
I expected all classes in the fflib-apex-mocks library to have a test coverage of at least 75%, as required by Salesforce for deployment.

**Screenshots and text of error observed**
Code coverage report showing the insufficient coverage for fflib_InvocationOnMock:
![image](https://github.com/apex-enterprise-patterns/fflib-apex-mocks/assets/25525300/259d2b00-14a7-4b58-84dc-5ef46176259b)

**Version**
The issue was observed with the latest version of the fflib-apex-mocks code available at the time of testing.

**Comment by ImJohnMDaniel** [comment]
@lb14447, this is not an issue because the entire codebase, when deployed together, gives more than code coverage.  The fact that one class is under 75% is not a concern.  

Thanks for raising the issue though.  

Please let us know if you have any other questions.
