### ISSUE TITLE
fflib_SObjectSelectorTest Error: 'Assertion Failed: Expected: 12345.67, Actual: 9117.25'

### ISSUE THREAD

**Issue by adayIvey** [apex-enterprise-patterns/fflib-apex-mocks#152]
**Describe the bug**
when I run the tests in 'fflib_SObjectSelectorTest Class' I get the following error.

System.AssertException: Assertion Failed: Expected: 12345.67, Actual: 9117.25
CODE LINE: system.assertEquals(12345.67,result[0].AnnualRevenue);

I think this has to do with our org being multi currency and there is a conversion  being applied on all currency fields in the Account object 

**To Reproduce**

Run test 'fflib_SObjectSelectorTest' from Developer Console in salesforce in a multi currency org

**Expected behavior**
All tests in class 'fflib_SObjectSelectorTest' pass and can handle currency correctly

**Version**
I just installed the latest version

**Comment by adayIvey** [comment]
Setting the CurrencyIsoCode = 'USD' when the account data is created in the test fixed the issue for me

List<Account> accountList = new List<Account> 
        {
			new Account(Name='TestAccount2',AccountNumber='A2',AnnualRevenue=12345.67, CurrencyIsoCode = 'USD'),
			new Account(Name='TestAccount1',AccountNumber='A1',AnnualRevenue=76543.21, CurrencyIsoCode = 'USD') 
		};

**Comment by ImJohnMDaniel** [comment]
Thanks for the update @adayIvey.  Glad to hear that you were able to resolve your issue.  Cheers!

**Comment by adayIvey** [comment]
While I did resolve my issue I think the test should be updated to include a currency code when creating Account Data
