### ISSUE TITLE
Spurious/scary SobjectExceptions in debug log for Matcher SObjectWith

### ISSUE THREAD

**Issue by cropredyHelix** [apex-enterprise-patterns/fflib-apex-mocks#62]
If your code does

    uow.registerDirty(someAccount);
    uow.registerDirty(someCase);

and you have these verifies:
```

((fflib_SobjectUnitOfWork) mocks.verify(mockUow,mocks.times(1)))
    		.registerDirty(fflib_Match.sObjectWith(new map<SObjectField,Object> {																
                      Account.ID => someAccountId}));

((fflib_SobjectUnitOfWork) mocks.verify(mockUow,mocks.times(1)))
    		.registerDirty(fflib_Match.sObjectWith(new map<SObjectField,Object> {																
                      Case.ID => someCaseId}));
```	

Then the debug log will show these exceptions

    System.SObjectException: Account.Id does not belong to SObject type Case
    System.SObjectException: Case.Id does not belong to SObject type Account				

**Investigation:**
* The Matcher for SObjectWith catches exception System.SObjectException and returns false as comparing a request to match Account for the registerDirty call on Case is in fact a no match (and vice-versa)

**Hence ...**
* While the code is WAD and even commented as a legit exception, the debug log to the casual debugger looks like something bad has happened and needs investigation

**Options**
* No good ones. 
* The `toMatch` is of type `Map<Schema.SObjectField, Object>` which doesn't tell you the type of Sobject the map is intended to match since there is no method to go from a `Schema.SObjectField` to an `SObjectType` (and this presumes that `toMatch` is constructed (sensibly) with only fields for the same SObjectType ..admittedly a nit)
* Ideally, one would compare `toMatch`'s implicit SObjectType with `soArg.getSobjectType()` and if different, return false and avoid throwing the SObjectExceptions.

**Comment by dfruddffdc** [comment]
Great writeup, thanks Eric!

For your specific case, you could use the sobjectWithId matcher. But I understand your general sentiment. It's a legitimate concern, but still kind of funny 🤣.

Recreating the exception is trivial.
```java
Account a = new Account();
a.get(Case.Id);
```

Or the similar, `SObject row was retrieved via SOQL without querying the requested field` exception, even if the field belongs to the object.
```java
for (Account a: [SELECT Id FROM Account]) {
	a.get(Account.Name);
}
```

Like you say, it's WAD. The matchers naively try to retrieve all the field values from all the SObject records, silently swallowing up the inevitable spurious exceptions.

So what to do..

As a  workaround, perhaps use a captor or a custom matcher instead?

But in ApexMocks itself.... You say we can't be more selective with the object type corresponding to the SObjectFields. But perhaps we can. We just need to supply the map as something that does have an associated SObjectType.... perhaps an SObject? :)

```java
public class SObjectWith implements fflib_IMatcher
{
	private SObject toMatch;

	public SObjectWith(SObject toMatch)
	{
		this.toMatch = validate(toMatch);
	}

	public Boolean matches(Object arg)
	{
		if (arg != null && arg instanceof SObject)
		{
			SObject soArg = (SObject)arg;
			if (soArg.getSObjectType() != this.toMatch.getSObjectType())
			{
				return false;
			}
			if (!sobjectMatches(soArg, this.toMatch.getPopulatedFieldsAsMap()))
			{
				return false;
			}
			return true;
		}

		return false;
	}
}
```

If you want to submit a PR along those lines, I'll be happy to review (also to include a version for a List<SObject>). Otherwise, I'll try and get this in at some point.

**Comment by cropredyHelix** [comment]
This is pretty clever; of course the old constructor that supports a map argument will need to continue to be supported.

**Comment by bradedge** [comment]
Hi team, any progress on this item? We are using mocks for integration tests. That is, the unit of work contains different object types. However, it appears we can not use mocks because of this limitation. Thank you!

**Comment by ImJohnMDaniel** [comment]
@bradedge -- Can you post a working example somewhere for us to review and investigate with?

**Comment by bradedge** [comment]
In our main class we have:

```
uow.registerDirty(transObj);
uow.registerDirty(invItemObj);
```
In our test class, this verify works:
```
((IApplicationSObjectUnitOfWork)
mocks.verify(uowMock, mocks.times(3).description('Expected 3 transaction updated.'))).registerDirty(
    fflib_Match.sObjectWith(
    new Map<SObjectField, Object>{
        Transaction__c.Order__c => orderList[0].Id
} ));
```
This next verify throws an error:
```
((IApplicationSObjectUnitOfWork) 
mocks.verify(uowMock, mocks.times(1).description('Expected 1 invoice item updated.'))).registerDirty(
    fflib_Match.sObjectWith(
    new Map<SObjectField, Object>{
        Invoice_Item__c.Order__c => orderList[0].Id,
} )); 

```
Error message: 
`fflib_ApexMocks.ApexMocksException: Expected : 1, Actual: 0 -- Wanted but not invoked IApplicationSObjectUnitOfWork__sfdc_ApexStub.registerDirty(SObject)`

The log file shows: 
`System.SObjectException: Invoice_Item__c.Order__c does not belong to SObject type Transaction__c`

**Comment by stohn777** [comment]
@bradedge
Is a stacktrace available for the error as well, indicating where in the FFLIB code the error is occurring?  Thanks.

**Comment by cropredyHelix** [comment]
The exception is normal in the debug log, the ApexMocks eats this error (you can see in the code).  Have you looked at [Why Aren't My ApexMocks working?](https://salesforce.stackexchange.com/questions/252460/my-apexmocks-arent-working-what-could-be-wrong).

I would say that `invItemObj` does not have field `Order__c` set to `orderList[0].Id` or, by the time the mocks.verify is executed, you've cleared/changed the value of `Order__c`

**Comment by bradedge** [comment]
@cropredyHelix, thank you. We have been through "Why Aren't My ApexMocks working?". 

When we read the issue you originally posted above, it describes the behavior we are getting and leads me to believe that mocks will not allow us to verify when we have multiple object types in the UOW (for example, in integration tests that perform actions on many object types).

Am incorrect? Does mocks allow us to verify multiple object types and you suspect we have an error elsewhere?

**Comment by bradedge** [comment]
I would appreciate some syntax help in a verify statement, to get through this item...   

We have successfully verified objects in the unit of work that were added using fflib_SObjectUnitOfWork.registerNew(SObject record) using this statement:

```
    ((IApplicationSObjectUnitOfWork)
    mocks.verify(uowMock, mocks.times(2).description(
        'Expected 2 invoices.'))).registerNew(
          fflib_Match.sObjectWith(
            new Map<SObjectField, Object>{
              Invoice__c.Order__c => orderList[0].Id
            }
          )
        );
```

However, this syntax does not work for records that were created using the overloaded "registerNew(SObject record, Schema.sObjectField relatedToParentField, SObject relatedToParentRecord)".

How do I match against items in the overloaded registerNew method? Thank you

**Comment by bradedge** [comment]
Failing on: 

   ```
   ((IApplicationSObjectUnitOfWork)
      mocks.verify(uowMock, mocks.times(2).description(
          'Expected 2 invoice items created for transList[0] and transList[2] (which goes on a new invoice and invoice item).'))).registerNew(
            fflib_Match.sObjectWith(
              new Map<SObjectField, Object>{
                Invoice_Item__c.Unit_Price__c => 5
              }
            )
          );
```
Stack trace:
```
Class.fflib_MethodVerifier.throwException: line 81, column 1
Class.fflib_AnyOrder.verify: line 45, column 1
Class.fflib_MethodVerifier.verifyMethodCall: line 20, column 1
Class.fflib_ApexMocks.verifyMethodCall: line 139, column 1
Class.fflib_ApexMocks: line 266, column 1
Class.fflib_ApexMocks: line 87, column 1
Class.IApplicationSObjectUnitOfWork__sfdc_ApexStub.registerNew: line 241, column 1
Class.InvoiceTransactionMockTest.singleOrderAndTranscationScenario1: line 145, column 1
12:40:55.0 (662859775)|FATAL_ERROR|fflib_ApexMocks.ApexMocksException: Expected : 2, Actual: 0 -- Wanted but not invoked: IApplicationSObjectUnitOfWork__sfdc_ApexStub.registerNew(SObject). Expected 2 invoice items created for transList[0] and transList[2] (which goes on a new invoice and invoice item).
```

**Comment by stohn777** [comment]
@bradedge,
That stacktrace appears related to the Assertion failure.  You mentioned an exception detailed in the log for "System.SObjectException: Invoice_Item__c.Order__c does not belong to SObject type Transaction__c".  Does a stacktrace exist for that?  Thanks again.

**Comment by cropredyHelix** [comment]
@bradedge 

1. You can definitely use UnitOfWork on multiple SobjectTypes and verify results using ApexMocks. Our org's code does this in numerous places
2. If you want to mock against `registerNew(SObject record, Schema.sObjectField relatedToParentField, SObject relatedToParentRecord)` ...


```
((IApplicationSObjectUnitOfWork)
   mocks.verify(uowMock, mocks.times(2).description(
       'Expected  invoice items created for transList[0] and [2] each with Unit Price of 5.00')))
      .registerNew(
         fflib_Match.sObjectWith(
           new Map<SObjectField, Object>{
             Invoice_Item__c.Unit_Price__c => 5
           }
         ),
         fflib_Match.eqSObjectField(Invoice_Item__c.Transaction__c),
	fflib_Match.sObjectOfType(Transaction__c.SobjectType)
       );

```

Now, if you are verifying that only Trans[0] and Trans[2] are linked, you'll need two different `mocks.verify`

For the first Invoice Item

```
((IApplicationSObjectUnitOfWork)
   mocks.verify(uowMock, mocks.times(1).description(
       'Expected  invoice items created for transList[0]  with Unit Price of 5.00')))
      .registerNew(
         fflib_Match.sObjectWith(
           new Map<SObjectField, Object>{
             Invoice_Item__c.Unit_Price__c => 5
           }
         ),
         fflib_Match.eqSObjectField(Invoice_Item__c.Transaction__c),
	 fflib_Match.sObjectWith(
          new Map<SObjectField, Object>{
             Transaction__c.Id => transList[0].Id
           }
        )
       );

```
For the second item

```
((IApplicationSObjectUnitOfWork)
   mocks.verify(uowMock, mocks.times(1).description(
       'Expected  invoice items created for transList[2]  with Unit Price of 5.00')))
      .registerNew(
         fflib_Match.sObjectWith(
           new Map<SObjectField, Object>{
             Invoice_Item__c.Unit_Price__c => 5
           }
         ),
         fflib_Match.eqSObjectField(Invoice_Item__c.Transaction__c),
	 fflib_Match.sObjectWith(
          new Map<SObjectField, Object>{
             Transaction__c.Id => transList[2].Id
           }
        )
       );

```

Now, perhaps I'm not understanding your use case but what you are trying to do is eminently doable. Each mocks.verify uses matchers against the method signature. If you use matchers for one arg, you have to use matchers for all args.

**Comment by bradedge** [comment]
@cropredyHelix that resolved our issue. Thank you all for the support and help through this! Also, thank you for supporting the community on this killer framework.

**Comment by daveespo** [comment]
Thanks all for pitching in here

**Comment by cropredyHelix** [comment]
@daveespo - not sure why this was closed as while we solved @bradedge issue, the underlying issue in OP was flagged as an enhancement by @dfruddffdc 2018-02-21.  Was the enhancement ever implemented? (perhaps in some other Issue)
