### ISSUE TITLE
Variable does not exist: Application.Service

### ISSUE THREAD

**Issue by Alex-Dinu** [apex-enterprise-patterns/fflib-apex-mocks#66]
I have the following test:
`        @isTest
    static void MockWhenHasNoOpportunitiesResponseSHouldBeFalse()
    {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        AlexMockExample2 mockEg2Object = (AlexMockExample2)mocks.factory(AlexMockExample2.class);
        
        mocks.startStubbing();
        mocks.when(mockEg2Object.GetNumberOfOpportunities()).thenReturn(0);
        mocks.stopStubbing();
        
        // Errors on this line.
        Application.Service.setMock(mockEg2Object.API.class, mockEg2Object);

        AlexMockExample1 eg1Object = new AlexMockExample1();
        
        Test.startTest();
        Boolean response = eg1Object.HasOpportunities();
        Test.stopTest();
        
        
        System.assertEquals(false, response);
        
        
    }`

But I get the following errors ::
Variable does not exist: Application.Service and Invalid type: mockEg2Object.API.

Commenting the line does not return the correct Integer defined in the stub.

I pushed all the classes into my sandbox. Do I need to do something with the .jar files?

What am I doing wrong here?

Thanks
Alex

**Comment by afawcett** [comment]
Some things to check...

Do you have an Application class in your sandbox? 
Do you have an mockEg2Object class in your sandbox?

**Comment by afawcett** [comment]
@Alex-Dinu closing this as I hope you got this sorted. Let me know if not. 👍
