### ISSUE TITLE
ID Generator fails on 1000th call due to use of Integer.format().

### ISSUE THREAD

**Issue by torynet** [apex-enterprise-patterns/fflib-apex-mocks#72]
Hey Apex Mocks team. First of all, thanks for the fantastically useful library and all your hard work.

I'm utilizing the ID generator in Apex Mocks. We're bulk testing where we are generating two hundred of each of several SObjects. This leads to the generator producing over 999 Ids. It then fails due to the , added by the format method. 

I have fixed this in our fork by utilizing String.valueOf() rather than Integer.format().
[fflib_IDGenerator.cls](https://github.com/financialforcedev/fflib-apex-mocks/blob/master/src/classes/fflib_IDGenerator.cls) Line 39
`
String fakeIdPrefix = ID_PATTERN.substring(0, 12 - fakeIdCount.format().length());
`
becomes
`
String fakeIdPrefix = ID_PATTERN.substring(0, 12 - String.valueOf(fakeIdCount).length());
`

I'm wondering if there is some reason that Integer.format() was used, which I may have missed. I just want to make sure I'm not causing another bug while I fix this one.

Thanks

p.s. Easy anonymous test code:
```
Set<Id> testIds = new Set<Id>();
for(Integer i = 0; i < 1000; i++){
    Id testId = fflib_IDGenerator.generate(Contact.SObjectType);
    System.debug('Test ' + i + ' Id: ' + testId);
	testIds.add(testId);
}
System.debug('Test Id Set: ' + testIds);
```

**Comment by torynet** [comment]
Well, that didn't format right at all, but it's there.

**Comment by afawcett** [comment]
Thank you!
