### ISSUE TITLE
fflib_QualifiedMethodAndArgValues test coverage

### ISSUE THREAD

**Issue by antonyxuan** [apex-enterprise-patterns/fflib-apex-mocks#74]
my production org is complaining about the test coverage for fflib_QualifiedMethodAndArgValues am I missing something?

**Comment by AllanOricil** [comment]
No, I runned the test coverage and it is really missing.

**Comment by AllanOricil** [comment]
![image](https://user-images.githubusercontent.com/55927613/66053435-3ad5fb80-e52a-11e9-9b96-587ecdbbfd8d.png)

**Comment by evanmcd** [comment]
Has anyone written tests for fflib_QualifiedMethodAndArgValues yet?

**Comment by daveespo** [comment]
Fixed via #90
