### ISSUE TITLE
Failure in Apex Mock Deploy 

### ISSUE THREAD

**Issue by meta-dwarika-vaishnav** [apex-enterprise-patterns/fflib-apex-mocks#93]
Deployment Started
Status: Queued 
Status: Completed 
Deployment Complete
Failures:
deploy/classes/fflib_ApexMocksUtils.cls(162,14):Method does not exist or incorrect signature: void writeFieldName(String) from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(163,14):Method does not exist or incorrect signature: void writeStartObject() from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(164,14):Method does not exist or incorrect signature: void writeNumberField(String, Integer) from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(165,14):Method does not exist or incorrect signature: void writeBooleanField(String, Boolean) from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(166,14):Method does not exist or incorrect signature: void writeFieldName(String) from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(168,14):Method does not exist or incorrect signature: void writeEndObject() from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(133,17):Illegal assignment from System.JSONGenerator to Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(137,42):Method does not exist or incorrect signature: void getAsString() from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(188,14):Method does not exist or incorrect signature: void writeStartArray() from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(192,14):Method does not exist or incorrect signature: void writeStartObject() from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(196,14):Method does not exist or incorrect signature: void writeFieldName(String) from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(202,14):Method does not exist or incorrect signature: void writeString(String) from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(204,14):Method does not exist or incorrect signature: void writeEndObject() from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtils.cls(208,14):Method does not exist or incorrect signature: void writeEndArray() from the type Jsongenerator
deploy/classes/fflib_ApexMocksUtilsTest.cls(162,14):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocksUtils : Method does not exist or incorrect signature: void writeFieldName(String) from the type Jsongenerator
deploy/classes/fflib_MatchTest.cls(162,14):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocksUtilsTest : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocksUtils : Method does not exist or incorrect signature: void writeFieldName(String) from the type Jsongenerator
deploy/classes/fflib_MatcherDefinitionsTest.cls(162,14):Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocksUtilsTest : Dependent class is invalid and needs recompilation:
 Class fflib_ApexMocksUtils : Method does not exist or incorrect signature: void writeFieldName(String) from the type Jsongenerator
classes/fflib_SystemTest.cls
classes/fflib_Inheritor.cls-meta.xml
classes/fflib_MatchTest.cls
classes/fflib_Answer.cls
classes/fflib_MethodArgValuesTest.cls
classes/fflib_InheritorTest.cls-meta.xml
classes/fflib_AnyOrder.cls
classes/fflib_InheritorTest.cls
classes/fflib_AnyOrderTest.cls-meta.xml
classes/fflib_ApexMocksUtilsTest.cls-meta.xml
classes/fflib_ApexMocksConfig.cls-meta.xml
classes/fflib_ApexMocksUtilsTest.cls
classes/fflib_MethodVerifier.cls-meta.xml
classes/fflib_SystemTest.cls-meta.xml
classes/fflib_ArgumentCaptor.cls
classes/fflib_ApexMocks.cls-meta.xml
classes/fflib_AnswerTest.cls-meta.xml
classes/fflib_MethodVerifier.cls
classes/fflib_MethodCountRecorder.cls-meta.xml
classes/fflib_Mocks.cls
classes/fflib_MyList.cls-meta.xml
classes/fflib_ArgumentCaptorTest.cls
classes/fflib_MethodArgValuesTest.cls-meta.xml
classes/fflib_ArgumentCaptorTest.cls-meta.xml
classes/fflib_MethodReturnValue.cls
classes/fflib_ApexMocksConfig.cls
classes/fflib_MatcherDefinitions.cls-meta.xml
classes/fflib_ApexMocks.cls
classes/fflib_MethodReturnValueRecorder.cls-meta.xml
classes/fflib_MethodReturnValue.cls-meta.xml
classes/fflib_Match.cls-meta.xml
classes/fflib_MatchersReturnValue.cls
classes/fflib_AnyOrder.cls-meta.xml
classes/fflib_InvocationOnMock.cls
classes/fflib_AnyOrderTest.cls
classes/fflib_QualifiedMethodAndArgValues.cls-meta.xml
classes/fflib_ApexMocksUtils.cls-meta.xml
classes/fflib_QualifiedMethod.cls-meta.xml
classes/fflib_InOrder.cls-meta.xml
classes/fflib_MethodReturnValueRecorder.cls
classes/fflib_ArgumentCaptor.cls-meta.xml
classes/fflib_Mocks.cls-meta.xml
classes/fflib_VerificationMode.cls-meta.xml
classes/fflib_ApexMocksUtils.cls
classes/fflib_System.cls-meta.xml
classes/fflib_Match.cls
classes/fflib_Answer.cls-meta.xml
classes/fflib_IMatcher.cls-meta.xml
classes/fflib_ApexMocksTest.cls
classes/fflib_MethodArgValues.cls-meta.xml
classes/fflib_QualifiedMethodAndArgValues.cls
classes/fflib_MatcherDefinitionsTest.cls
classes/fflib_MyList.cls
classes/fflib_IDGenerator.cls
classes/fflib_Inheritor.cls
classes/fflib_InOrderTest.cls-meta.xml
classes/fflib_InOrder.cls
classes/fflib_MethodCountRecorder.cls
classes/fflib_AnswerTest.cls
classes/fflib_QualifiedMethodTest.cls-meta.xml
classes/fflib_IMatcher.cls
classes/fflib_ApexMocksTest.cls-meta.xml
classes/fflib_MethodArgValues.cls
classes/fflib_VerificationMode.cls
classes/fflib_IDGeneratorTest.cls
classes/fflib_QualifiedMethod.cls
classes/fflib_IDGenerator.cls-meta.xml
classes/fflib_IDGeneratorTest.cls-meta.xml
classes/fflib_MatcherDefinitions.cls
classes/fflib_MatchersReturnValue.cls-meta.xml
classes/fflib_InOrderTest.cls
classes/fflib_MatchTest.cls-meta.xml
classes/fflib_MatcherDefinitionsTest.cls-meta.xml
classes/fflib_QualifiedMethodTest.cls
classes/fflib_InvocationOnMock.cls-meta.xml
classes/fflib_System.cls
package.xml

**Comment by ImJohnMDaniel** [comment]
@meta-dwarika-vaishnav -- Can I ask that you try the deployment again?  I just pulled the latest codebase and deployed with no issue.  

The errors that you are showing don't make sense.  Most of them mentioned the type `JSONGenerator` is not valid but `JSONGenerator` is a standard platform class (ref [Apex Developer Docs here](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_System_JsonGenerator.htm))

**Comment by briancodey** [comment]
@ImJohnMDaniel - When I tried to deploy the fflib-apex-mocks library, I got the following errors, which was really odd:

`force-app/main/default/classes/fflib_ApexMocksUtilsTest.cls      Variable does not exist: LastReferencedDate (238:44)                                  
force-app/main/default/classes/fflib_ApexMocksUtilsTest.cls      Variable does not exist: LastReferencedDate (242:40)`

I ran this code in Dev Console successfully:

`DateTime lastRefDate = DateTime.newInstanceGmt(2020, 1, 7, 23, 30, 0);
Map<SObjectField, Object> properties = new Map<SObjectField, Object> {Account.LastReferencedDate => lastRefDate};
`

Did I miss anything?

**Comment by ImJohnMDaniel** [comment]
G'day @briancodey 

- are you deploying to a scratch org or to a sandbox?
- is the environment on #Spring20 release or on a preview release of #Summer20?

**Comment by briancodey** [comment]
Hi @ImJohnMDaniel ,

- I am deploying to a developer environment.
- The environment is on @Spring20.

**Comment by ImJohnMDaniel** [comment]
So the deployment succeeds but the fflib_ApexMocksUtilsTest fails executing or you can't deploy the code at all?

**Comment by briancodey** [comment]
I could not deploy the code at all as the process stopped when it encountered the error.

**Comment by ImJohnMDaniel** [comment]
Understood.  

I have deployed the master branch code of the project to a DX Scratch org and a DE org with no issues.  

- Are you consistently getting this error with every deployment attempt?
- Is there anything special that you can see with DE org?  
- What tool are you using to deploy the codebase?  Salesforce CLI?  Something else?

**Comment by briancodey** [comment]
Properly the way I deployed wasn't the efficient way, but I cloned the fflib-apex-mocks repo, then copied to code files to my DE org classes folder and then use VSCodes to deploy to my DE Org.

**Comment by ImJohnMDaniel** [comment]
Yeah, that sounds like the potential issue.  

Any reason that you are not using VS Code with Salesforce Extension Pack and the underlying Salesforce CLI to handle the deployment?

**Comment by briancodey** [comment]
I had Salesforce Extension Pack.  I used the VSCode UI deploy.  What I did was right click on the Classes folder and chose SFDX: Deploy Source to Org.  That was really CLI in the background.

I can try using CLI command.

**Comment by ctchipps** [comment]
@briancodey @meta-dwarika-vaishnav Hi, I am (hoping) that you all were able to overcome this issue? If so, would you mind to close this issue. Thank you!

**Comment by daveespo** [comment]
Closing since this sounds resolved
