### ISSUE TITLE
Update API version to 51 (Spring '21) for all Apex classes

### ISSUE THREAD

**Issue by daveespo** [apex-enterprise-patterns/fflib-apex-mocks#97]
The Apex classes in this repo appear to be at version 37 -- let's update to 48

**Comment by ctchipps** [comment]
@daveespo @ImJohnMDaniel I will raise a PR to update the API version to 50.0 (given that all tests pass) after we merge #108 to solve the unreachable statement issue.

**Comment by daveespo** [comment]
@ctchipps  -- I propose that we wait 3 weeks until Spring '21 finishes rolling out and go to API 51 since there is a bug over in fflib-apex-common (https://github.com/apex-enterprise-patterns/fflib-apex-common/issues/309) that is supposedly fixed in API 51 and I'd like to do this all in one shot

I'm updating the Summary of this issue to reflect what we really want to do here

**Comment by ctchipps** [comment]
@daveespo Wholeheartedly agree, I will standby on that PR until Spring '21 completes.

**Comment by ctchipps** [comment]
@daveespo Let's close this from #112

**Comment by daveespo** [comment]
Agreed, thanks; linked 'em up
